### ISSUE TITLE
Error: no such method 'reload' for sortable widget instance

### ISSUE THREAD

**Issue by larjohn** [lukasoppermann/html5sortable#43]
For angular v1.2.24 I get 

Error: no such method 'reload' for sortable widget instance
    at Function.jQuery.extend.error (http://localhost/beanbid/public/bower_resources/jquery/dist/jquery.js:250:9)
    at HTMLUListElement.<anonymous> (http://localhost/beanbid/public/bower_resources/jquery-ui/jquery-ui.js:511:15)
    at Function.jQuery.extend.each (http://localhost/beanbid/public/bower_resources/jquery/dist/jquery.js:375:23)
    at jQuery.fn.jQuery.each (http://localhost/beanbid/public/bower_resources/jquery/dist/jquery.js:139:17)
    at $.fn.(anonymous function) [as sortable](http://localhost/beanbid/public/bower_resources/jquery-ui/jquery-ui.js:499:9)
    at http://localhost/beanbid/public/bower_resources/html.sortable/dist/html.sortable.angular.js:34:27
    at http://localhost/beanbid/public/bower_resources/angularjs/angular.js:14304:28
    at completeOutstandingRequest (http://localhost/beanbid/public/bower_resources/angularjs/angular.js:4397:10)
    at http://localhost/beanbid/public/bower_resources/angularjs/angular.js:4705:7

**Comment by bdauton** [comment]
Hi,

Got the same error and I had to include html.sortable.js too (just before html.sortable.angular.js).

**Comment by larjohn** [comment]
This was not enough for me. I had to remove jquery-ui from the loaded scripts to have the error go away.

**Comment by lukasoppermann** [comment]
So is this solved? Is there a need for more documentation, if so please provide a suggestion or a PR with additions to the readme.

**Comment by lukasoppermann** [comment]
Closing this for now, if this happens again, please reopen with a fix or something to add to the docs.
